# https://bretahajek.com/2016/11/electron-builder-appveyor-travis-ci-memory-king/
sudo: required
dist: trusty

language: c

node_js:
- 7

cache:
  directories:
  - node_modules

install:
- nvm install 7
- npm install

jobs:
  include:
  - stage: deploy
    name: "Deploy to gh-pages"
    script:
    - npm run deploy
